services:
  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  userservice:
    image: userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=OrderProcessingSystemDB
        
  inventoryservice:
    image: inventoryservice
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=OrderProcessingSystemDB


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

